### ISSUE TITLE
Menu stimmt nicht

### ISSUE THREAD

**Issue by Fightbackman** [td--/kf#5]
Wenn man auf der Startseite auf Kontakt klickt, scrollt das ganze zwar runter zum Kontaktfeld, aber das Menu am linken Rand verändert den hervorgehobenen Bereich nicht entsprechend.

**Comment by thies23** [comment]
Skript stimmt.
Mach mal noscript aus.

**Comment by Fightbackman** [comment]
noscript ist aus
hab auf der seite alles deaktiviert

**Comment by thies23** [comment]
Oops.
Tatsache.
Hatte nur die Sidebar gecheckt.
Ich reopen das mal und fix es gleich.

**Comment by thies23** [comment]
Menüpunkt gelöscht.
Nurnoch per Sidebar navigierbar.
